[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
version = { attr = "astroberry_manager.main.__version__" }

[project]
name = "astroberry_manager"
dynamic = ["version", "dependencies"]
authors = [{ name="Radek Kaczorek", email="rkaczorek@gmail.com" }]
description = "Astroberry Manager is a web interface for Astroberry OS"
readme = "README.md"
requires-python = ">=3.9"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
classifiers = [
    'Natural Language :: English',
    'Programming Language :: Python',
    'Operating System :: OS Independent',
    'Intended Audience :: Science/Research',
    'Topic :: Scientific/Engineering :: Astronomy',
]

[project.scripts]
astroberry-manager = "astroberry_manager.main:main"

[project.urls]
Homepage = "https://www.astroberry.io/"
Issues = "https://github.com/astroberry-official/astroberry-manager/issues"
