#!/bin/bash
# postrm script for astroberry-manager

set -e

if [ "$1" == "remove" -o "$1" == "purge" ]; then

        # disable required services
        rm -rf /etc/systemd/system/multi-user.target.wants/vncserver.service
        rm -rf /etc/systemd/system/multi-user.target.wants/websockify.service
        rm -rf /etc/systemd/system/multi-user.target.wants/indiwebmanager.service
	rm -rf /etc/systemd/system/multi-user.target.wants/astroberry-manager.service

	if [ -e /etc/caddy/Caddyfile.default ]; then
		mv /etc/caddy/Caddyfile /etc/caddy/Caddyfile.bak
		mv /etc/caddy/Caddyfile.default /etc/caddy/Caddyfile
	fi

	if [ -e /opt/astroberry-manager/.venv ]; then
	        rm -rf /opt/astroberry-manager/.venv
	fi

	if [ -n "$(find /opt/astroberry-manager -maxdepth 0 -type d -empty 2>/dev/null)" ]; then
		rm -rf /opt/astroberry-manager
	fi
fi
